Repository selsa-inube/inubekit-label, pull requests merged in 2024-02, with the labels that each got.

#4 Component refactoring to use the new token structure
  package-lock.json
  package.json
  src/Label/Label.stories.tsx
  src/Label/styles.js
  src/Label/typography.ts
  vite.config.ts
Labels: minor

#5 Adjust package.json for release script
  package.json
Labels: patch

#6 Publish new version 1.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation
